#!perl
#
# Install script for ToPDFPlugin
#
# Copyright (C) 2004-2007 Foswiki Contributors. All Rights Reserved.
# Foswiki Contributors are listed in the AUTHORS file in the root of
# this distribution. NOTE: Please extend that file, not this notice.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version. For
# more details read LICENSE in the root of this distribution.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# As per the GPL, removal of this notice is prohibited.
#
# Author: Crawford Currie http://c-dot.co.uk
#
# NOTE TO THE DEVELOPER: THIS FILE IS GENERATED AUTOMATICALLY
# BY THE BUILD PROCESS DO NOT EDIT IT - IT WILL BE OVERWRITTEN
#
use strict;
use warnings;
require 5.008;

use File::Spec;
use Cwd;

=pod

---+ ToPDFPlugin_installer
This is the installer script. The basic function of this script is to
locate an archive and unpack it.

It will also check the dependencies listed in DEPENDENCIES and assist
the user in installing any that are missing. The script also automatically
maintains the revision histories of any files that are being installed by the
package but already have ,v files on disc (indicating that they are
revision controlled).

The script also functions as an *uninstaller* by passing the parameter
=uninstall= on the command-line. Note that uninstallation does *not* revert
the history of any topic changed during the installation.

The script allows the definition of PREINSTALL and POSTINSTALL scripts.
These scripts can be used for example to modify the configuration during
installation, using the functions described below.

Refer to the documentation of =configure=

=cut

# This is all done in package Foswiki so that reading LocalSite.cfg and Foswiki.cfg
# will put the config vars into the right namespace.
package Foswiki;

# The root of package URLs
my $PACKAGES_URL = 'http://foswiki.org/pub/Extensions';

# Extract MANIFEST and DEPENDENCIES from the __DATA__
undef $/;
my @DATA = split( /<<<< (.*?) >>>>\s*\n/, <DATA> );
shift @DATA;    # remove empty first element

# Establish where we are
my @path = ( 'tools', 'extender.pl' );
my $wd = Cwd::cwd();
$wd =~ /^(.*)$/;    # untaint
unshift( @path, $1 ) if $1;
my $script = File::Spec->catfile(@path);

unless ( my $return = do $script ) {
    my $message = <<MESSAGE;
************************************************************
Could not load $script
MESSAGE
    if ($@) {
        $message .= "There was a compile error: $@\n";
    }
    elsif (defined $return) {
        $message .= "There was a file error: $!\n";
    }
    else {
        $message .= "An unspecified error occurred\n";
    }
    $message .= <<MESSAGE;
(if this is a TWiki release prior to 4.2, you can download this
 file from: http://twiki.org/cgi-bin/view/Codev/ExtenderScript
 and place it in
 $wd/tools
 Create the directory if necessary).
************************************************************
MESSAGE

    # Try again, using open. This cures some uncooperative platforms.
    if ( open( F, '<', $script ) ) {
        local $/;
        my $data = <F>;
        close(F);
        $data =~ /^(.*)$/s;    # untaint
        eval $1;
        if ($@) {
            $message .= "Error when trying to eval the file content: $@\n";
        }
        else {
            print STDERR
              "'do $script failed, but install was able to proceed: $message";
            undef $message;
        }
    }
    else {
        $message .= "Could not open file using open() either: $!\n";
    }
    die $message if $message;
}

sub preuninstall {

    # # No PREUNINSTALL script;
}

sub postuninstall {

    # # No POSTUNINSTALL script;
}

sub preinstall {

    # # No PREINSTALL script;
}

sub postinstall {

    # # No POSTINSTALL script;
}

Foswiki::Extender::install( $PACKAGES_URL, 'ToPDFPlugin', 'ToPDFPlugin', @DATA );

1;

# MANIFEST and DEPENDENCIES are done this way
# to make it easy to extract them from this script.

__DATA__
<<<< MANIFEST >>>>
data/System/ToPDFPlugin.txt,0664,Plugin topic
data/System/ToPDFPluginHeader.txt,0664,Plugin topic
data/System/ToPDFPluginFooter.txt,0664,Plugin topic
lib/Foswiki/Plugins/ToPDFPlugin.pm,0444,Plugin Perl module
lib/Foswiki/Plugins/ToPDFPlugin/Config.spec,0644,
pub/System/ToPDFPlugin/html2pdf/box.input.img.php,0664,
pub/System/ToPDFPlugin/html2pdf/observer.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/html.attrs.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/value.border.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.property.sub.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/encoding.koi8-r.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/pipeline.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.border.right.color.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.margin.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/box.button.reset.php,0664,
pub/System/ToPDFPlugin/html2pdf/output.png.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/output.pdflib.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/value.top.php,0664,
pub/System/ToPDFPlugin/html2pdf/fetcher.local.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/box.utils.text-align.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.border.bottom.color.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.color.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/data/LineBreak.txt,0664,
pub/System/ToPDFPlugin/html2pdf/css.page-break-after.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.direction.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/tag.body.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/xhtml.p.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/tag.span.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/destination.browser.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/value.content.item.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.min-width.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.border.top.style.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.font-weight.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.word-spacing.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/box.radiobutton.php,0664,
pub/System/ToPDFPlugin/html2pdf/html2ps.config,0664,
pub/System/ToPDFPlugin/html2pdf/css.overflow.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/tag.td.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/output._generic.ps.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.line-height.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.pseudo.cellspacing.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.property.handler.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/autofix.url.php,0664,
pub/System/ToPDFPlugin/html2pdf/output.fastps.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/encoding.symbol.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/value.padding.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/xhtml.entities.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.background.position.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/box.table.cell.fake.php,0664,
pub/System/ToPDFPlugin/html2pdf/dom.php5.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.table-layout.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/ps.whitespace.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/pdf.fpdf.makefont.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.pseudo.cellpadding.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/output.pdflib.1.6.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/box.button.submit.php,0664,
pub/System/ToPDFPlugin/html2pdf/utils_url.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.selectors.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/font.constants.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.pseudo.add.margin.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/misc/logger.php,0664,
pub/System/ToPDFPlugin/html2pdf/background.position.php,0664,
pub/System/ToPDFPlugin/html2pdf/render.stacking.level.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/tag.img.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.pseudo.table.border.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.size.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/pdf.fpdf.encryption.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.border.bottom.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/utils_text.php,0664,
pub/System/ToPDFPlugin/html2pdf/value.max-height.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.border.top.color.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.parse.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.page-break-before.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/value.content.php,0664,
pub/System/ToPDFPlugin/html2pdf/value.border.width.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/ps.image.encoder.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/encoding.iso-8859-8.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/xhtml.tables.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/box.table.cell.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.border.left.color.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/fetched_data._html.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/box.button.php,0664,
pub/System/ToPDFPlugin/html2pdf/fetcher.url.curl.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.border.top.width.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/value.line-height.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.html2ps.pixels.php,0664,
pub/System/ToPDFPlugin/html2pdf/dispatcher.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/encoding.cp1251.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/templates/error._missing_afm.tpl,0664,
pub/System/ToPDFPlugin/html2pdf/templates/error_exec.tpl,0664,
pub/System/ToPDFPlugin/html2pdf/templates/error._no_fetchers.tpl,0664,
pub/System/ToPDFPlugin/html2pdf/templates/cannot_parse.html,0664,
pub/System/ToPDFPlugin/html2pdf/templates/error._footer.tpl,0664,
pub/System/ToPDFPlugin/html2pdf/templates/missing_url_fopen.html,0664,
pub/System/ToPDFPlugin/html2pdf/templates/error._redirects.tpl,0664,
pub/System/ToPDFPlugin/html2pdf/templates/missing_gs.html,0664,
pub/System/ToPDFPlugin/html2pdf/templates/error._header.tpl,0664,
pub/System/ToPDFPlugin/html2pdf/templates/missing_pdflib.html,0664,
pub/System/ToPDFPlugin/html2pdf/templates/error._http.tpl,0664,
pub/System/ToPDFPlugin/html2pdf/templates/error._connection.tpl,0664,
pub/System/ToPDFPlugin/html2pdf/templates/missing_exec.html,0664,
pub/System/ToPDFPlugin/html2pdf/css.rules.page.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.css.background.attachment.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.float.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.position.horizontal.absolute.positioned.1.html,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.left.percentage.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.input.select.height.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.pagebreak.table.br.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.white-space.1.html,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.css.parse.atrules.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.css.parse.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.size.length.html,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/fetcher.memory.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.size.predefined.portrait.html,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.tag.ol.type.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.white-space.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.css.page.break.before.1.html,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.iframe.src.missing.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.size.predefined.html,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.toc.unicode.html,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.css.content.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.border-left.1.html,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.pagebreak.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.orphans.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.border-right.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.page.margins.fixed.subproperties.html,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.css.page.break.after.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.table.column.width.4.html,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.border-left.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.css.page.break.inside.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.size.flow.html,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.orphans.inherit.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.border-right.1.html,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.containing.block.absolute.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.page.pixels.html,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.border-top.1.html,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.css.content.1.html,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.pagebreak.table.lines.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.html.mode.1.html,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.pagebreak.text.1.html,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.textarea.width.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.css.page.break.after.1.html,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.input.text.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.css.page.break.before.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.position.horizontal.absolute.positioned.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.css.priority.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.iframe.src.empty.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.table.column.width.2.html,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.textarea.content.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.pagebreak.text.2.html,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.width.absolute.positioned.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.img.align.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.tag.ol.type.html,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.link.1.html,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.line-box.nested.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.table.border.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.table.column.width.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.relative.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/sample,0664,css.css
pub/System/ToPDFPlugin/html2pdf/unittest/test.note-call.width.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.block.absolute.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.line-height.100.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.widows.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.white-space.2.html,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.page.margins.percentage.html,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.border-top.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/generic.test.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.pagebreak.table.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.page.margins.fixed.html,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.textarea.wrap.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.table.absolute.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.autofix.url.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.html.mode.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.textarea.height.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.css.content.string.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.pagebreak.border.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.radio.png.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.css.page.break.after.2.html,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.toc.find.html,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.table.column.width.3.html,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.input.text.height.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.width.percentage.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.pagebreak.fixed.height.1.html,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.pagebreak.fixed.height.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.parser.8.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.parser.5.css,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.parser.error.5.css,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.default.header.html,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.process.2.html,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.process.1.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.parser.9.css,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.process.import.html,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.parser.error.8.css,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.process.3.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.process.margin.left.html,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.parser.2.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.process.margin.html,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.process.padding.html,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.parser.error.5.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/suite.style.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.lexer.comment.long.css,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.process.6.html,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.process.8.html,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.process.margin.left.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.style.1.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.parser.7.css,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.process.1.html,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.parser.3.css,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.parser.error.7.css,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.parser.error.6.css,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.process.7.html,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.parser.error.4.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.default.footer.html,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/run.bat,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.process.padding.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.parser.error.6.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.parser.11.css,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.process.5.html,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.parser.4.css,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.lexer.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.parser.error.2.css,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.parser.error.1.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.parser.6.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.lexer.comment.long.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/suite.errors.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.process.class.case.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.process.3.html,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.parser.2.css,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.parser.9.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/suite.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.lexer.1.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.parser.7.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.parser.10.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.parser.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.parser.3.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.parser.11.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.default.1.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.parser.error.2.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.parser.error.4.css,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.parser.8.css,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.process.import.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.process.8.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.parser.5.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.parser.6.css,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.process.2.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.parser.10.css,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/coverage.bat,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.parser.error.3.css,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/suite.default.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.process.6.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.process.4.html,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/suite.parser.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.process.class.case.html,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/suite.process.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.process.7.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.parser.error.8.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/_generic.test.lexer.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.process.4.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.parser.error.1.css,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/suite.log,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.process.margin.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.parser.12.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.parser.1.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.parser.error.3.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.parser.error.7.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.parser.4.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.lexer.2.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.parser.1.css,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/suite.lexer.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.parser.12.css,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/css/test.process.5.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.font-size.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.line-box.top.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.size.predefined.landscape.html,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.border-bottom.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.link.2.html,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.border-bottom.1.html,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.tag.ul.type.html,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.size.lengths.html,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.table.top-boundary.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.text-transform.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/index.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.link.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.width.absolute.positioned.1.html,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.pagebreak.br.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.tag.ul.type.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.font.inherit.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.table.column.width.1.html,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.css.margin.boxes.php,0664,
pub/System/ToPDFPlugin/html2pdf/unittest/test.table.border.nested.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.pseudo.listcounter.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/fetched_data.file.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/strategy.table.layout.auto.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.background.repeat.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.border.collapse.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/box.whitespace.php,0664,
pub/System/ToPDFPlugin/html2pdf/ot.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/value.generic.length.php,0664,
pub/System/ToPDFPlugin/html2pdf/inline.content.builder.pre.line.php,0664,
pub/System/ToPDFPlugin/html2pdf/strategy.width.min.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.border.right.width.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.property.collection.php,0664,
pub/System/ToPDFPlugin/html2pdf/filter.data.ucs2.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.visibility.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/inline.content.builder.factory.php,0664,
pub/System/ToPDFPlugin/html2pdf/parser.xhtml.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/default.css,0664,
pub/System/ToPDFPlugin/html2pdf/ps.unicode.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/filter.pre.footnotes.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.colors.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/encoding.iso-8859-1.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/stubs.common.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.counter.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.text-align.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/encoding.windows-1252.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/cache/.ignore,0664,
pub/System/ToPDFPlugin/html2pdf/stubs._.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/font.resolver.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/value.border.style.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/destination._http.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/image.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/box.br.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.position.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/config.parse.php,0664,
pub/System/ToPDFPlugin/html2pdf/box.form.php,0664,
pub/System/ToPDFPlugin/html2pdf/layout/box.inline.php,0664,
pub/System/ToPDFPlugin/html2pdf/layout/box.php,0664,
pub/System/ToPDFPlugin/html2pdf/tree.navigation.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/font.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/box.generic.inline.php,0664,
pub/System/ToPDFPlugin/html2pdf/render.queue.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.widows.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/filter.post.postponed.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/encoding.iso-8859-15.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/box.select.php,0664,
pub/System/ToPDFPlugin/html2pdf/tag.table.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/box.inline.control.php,0664,
pub/System/ToPDFPlugin/html2pdf/.ignore,0664,
pub/System/ToPDFPlugin/html2pdf/fetcher.url.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/ChangeLog,0664,
pub/System/ToPDFPlugin/html2pdf/css.text-indent.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/xhtml.selects.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/dom.activelink.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/output.pdflib.old.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/fpdf/font/makefont/cp1254.map,0664,
pub/System/ToPDFPlugin/html2pdf/fpdf/font/makefont/cp874.map,0664,
pub/System/ToPDFPlugin/html2pdf/fpdf/font/makefont/cp1250.map,0664,
pub/System/ToPDFPlugin/html2pdf/fpdf/font/makefont/cp1255.map,0664,
pub/System/ToPDFPlugin/html2pdf/fpdf/font/makefont/koi8-r.map,0664,
pub/System/ToPDFPlugin/html2pdf/fpdf/font/makefont/iso-8859-2.map,0664,
pub/System/ToPDFPlugin/html2pdf/fpdf/font/makefont/iso-8859-11.map,0664,
pub/System/ToPDFPlugin/html2pdf/fpdf/font/makefont/iso-8859-16.map,0664,
pub/System/ToPDFPlugin/html2pdf/fpdf/font/makefont/cp1251.map,0664,
pub/System/ToPDFPlugin/html2pdf/fpdf/font/makefont/iso-8859-9.map,0664,
pub/System/ToPDFPlugin/html2pdf/fpdf/font/makefont/iso-8859-15.map,0664,
pub/System/ToPDFPlugin/html2pdf/fpdf/font/makefont/symbol.map,0664,
pub/System/ToPDFPlugin/html2pdf/fpdf/font/makefont/cp1252.map,0664,
pub/System/ToPDFPlugin/html2pdf/fpdf/font/makefont/iso-8859-7.map,0664,
pub/System/ToPDFPlugin/html2pdf/fpdf/font/makefont/cp1253.map,0664,
pub/System/ToPDFPlugin/html2pdf/fpdf/font/makefont/cp1258.map,0664,
pub/System/ToPDFPlugin/html2pdf/fpdf/font/makefont/iso-8859-4.map,0664,
pub/System/ToPDFPlugin/html2pdf/fpdf/font/makefont/makefont.php,0664,
pub/System/ToPDFPlugin/html2pdf/fpdf/font/makefont/iso-8859-5.map,0664,
pub/System/ToPDFPlugin/html2pdf/fpdf/font/makefont/cp1257.map,0664,
pub/System/ToPDFPlugin/html2pdf/fpdf/font/makefont/koi8-u.map,0664,
pub/System/ToPDFPlugin/html2pdf/fpdf/font/makefont/iso-8859-1.map,0664,
pub/System/ToPDFPlugin/html2pdf/fpdf/fpdf.php,0664,
pub/System/ToPDFPlugin/html2pdf/strategy.table.layout.fixed.php,0664,
pub/System/ToPDFPlugin/html2pdf/box.page.php,0664,
pub/System/ToPDFPlugin/html2pdf/manager.encoding.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.property.stringset.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.orphans.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/box.iframe.php,0664,
pub/System/ToPDFPlugin/html2pdf/fetcher._interface.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.constants.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/features/watermark.php,0664,
pub/System/ToPDFPlugin/html2pdf/features/encryption.php,0664,
pub/System/ToPDFPlugin/html2pdf/features/automargins.php,0664,
pub/System/ToPDFPlugin/html2pdf/features/toc.php,0664,
pub/System/ToPDFPlugin/html2pdf/features/_factory.php,0664,
pub/System/ToPDFPlugin/html2pdf/encoding.windows-1250.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.bottom.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.pseudo.form.radiogroup.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/box.input.password.php,0664,
pub/System/ToPDFPlugin/html2pdf/strategy.page.break.simple.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.background.image.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.page-break-inside.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/box.img.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.background.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.text-transform.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/stubs.memory_get_usage.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/encoding.iso-8859-6.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/filter.data.encoding.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/width.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.font.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/flow_context.class.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/box.container.php,0664,
pub/System/ToPDFPlugin/html2pdf/font_factory.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.rules.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/out/readme.txt,0664,
pub/System/ToPDFPlugin/html2pdf/css.border.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/fetched_data._interface.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/output._generic.pdf.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/xhtml.script.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/box.legend.php,0664,
pub/System/ToPDFPlugin/html2pdf/utils_number.php,0664,
pub/System/ToPDFPlugin/html2pdf/value.border.color.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/filter.post._interface.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/xml.validation.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/ps.image.encoder.simple.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/xhtml.comments.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/strategy.width.min.nowrap.php,0664,
pub/System/ToPDFPlugin/html2pdf/encoding.iso-8859-7.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.border.color.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/value.background.php,0664,
pub/System/ToPDFPlugin/html2pdf/encoding.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.page.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/value.bottom.php,0664,
pub/System/ToPDFPlugin/html2pdf/fetcher.memory.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/1,0664,
pub/System/ToPDFPlugin/html2pdf/css.width.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.white-space.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/filter.data.doctype.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.min-height.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/box.input.text.php,0664,
pub/System/ToPDFPlugin/html2pdf/filter.data.html2xhtml.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.top.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/encoding.iso-8859-14.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/box.inline.php,0664,
pub/System/ToPDFPlugin/html2pdf/encoding.cp866.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/box.page.margin.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.content.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/box.note-call.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/treebuilder.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.border.right.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/box.generic.formatted.php,0664,
pub/System/ToPDFPlugin/html2pdf/LICENSE,0664,
pub/System/ToPDFPlugin/html2pdf/css.background.attachment.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.background.color.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.parse.properties.php,0664,
pub/System/ToPDFPlugin/html2pdf/box.table.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.border.bottom.width.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/output._generic.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/.htaccess,0664,
pub/System/ToPDFPlugin/html2pdf/content_type.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/path.php,0664,
pub/System/ToPDFPlugin/html2pdf/globals.php,0664,
pub/System/ToPDFPlugin/html2pdf/utils_units.php,0664,
pub/System/ToPDFPlugin/html2pdf/box.table.section.php,0664,
pub/System/ToPDFPlugin/html2pdf/render.stacking.context.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/box.body.php,0664,
pub/System/ToPDFPlugin/html2pdf/tag.input.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/parser._interface.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.clear.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/value.list-style.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/xhtml.deflist.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/filter.data._interface.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/box.null.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.html2ps.pseudoelements.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/box.input.textarea.php,0664,
pub/System/ToPDFPlugin/html2pdf/stubs.file_get_contents.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/box.text.string.php,0664,
pub/System/ToPDFPlugin/html2pdf/encoding.iso-8859-10.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/inline.content.builder.pre.wrap.php,0664,
pub/System/ToPDFPlugin/html2pdf/xhtml.style.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/flow_viewport.class.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/xhtml.utils.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/destination.file.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/box.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.frame.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/strategy.link.rendering.normal.php,0664,
pub/System/ToPDFPlugin/html2pdf/output.fpdf.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/filter.post.positioned.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/value.generic.php,0664,
pub/System/ToPDFPlugin/html2pdf/tag.frame.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/box.block.inline.php,0664,
pub/System/ToPDFPlugin/html2pdf/filter.output.ps2pdf.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/box.inline.simple.php,0664,
pub/System/ToPDFPlugin/html2pdf/encoding.iso-8859-11.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/list-style.image.php,0664,
pub/System/ToPDFPlugin/html2pdf/value.font.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/value.left.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.border.left.width.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/html2ps.config.recommended,0664,
pub/System/ToPDFPlugin/html2pdf/css.border.bottom.style.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/box.field.pageno.php,0664,
pub/System/ToPDFPlugin/html2pdf/box.table.row.php,0664,
pub/System/ToPDFPlugin/html2pdf/layout.vertical.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.border.right.style.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/.cvsignore,0664,
pub/System/ToPDFPlugin/html2pdf/layout.page.breaks.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.pseudo.link.destination.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/strategy.width.absolute.positioned.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.border.left.style.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/filter.pre.headfoot.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/box.text.php,0664,
pub/System/ToPDFPlugin/html2pdf/xhtml.autoclose.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.padding.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/dombuilder.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.text-decoration.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/encoding.iso-8859-2.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/stubs.file_put_contents.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/inline.content.builder.pre.php,0664,
pub/System/ToPDFPlugin/html2pdf/encoding.iso-8859-13.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.utils.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/samples/sample.simplest.from.memory.php,0664,
pub/System/ToPDFPlugin/html2pdf/samples/sample.pipeline.custom.php,0664,
pub/System/ToPDFPlugin/html2pdf/samples/sample.form.handler.php,0664,
pub/System/ToPDFPlugin/html2pdf/samples/out/readme.txt,0664,
pub/System/ToPDFPlugin/html2pdf/samples/sample.simplest.from.file.php,0664,
pub/System/ToPDFPlugin/html2pdf/samples/sample.simplest.php,0664,
pub/System/ToPDFPlugin/html2pdf/samples/sample.batch.php,0664,
pub/System/ToPDFPlugin/html2pdf/samples/sample.pipeline.default.php,0664,
pub/System/ToPDFPlugin/html2pdf/samples/API/events/1/test.html,0664,
pub/System/ToPDFPlugin/html2pdf/samples/API/events/1/html2pdf.php,0664,
pub/System/ToPDFPlugin/html2pdf/tag.font.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/converter.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/background.image.php,0664,
pub/System/ToPDFPlugin/html2pdf/encoding.iso-8859-4.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/utils_array.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.pseudo.nowrap.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/value.height.php,0664,
pub/System/ToPDFPlugin/html2pdf/ps.l3.image.encoder.stream.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/box.block.php,0664,
pub/System/ToPDFPlugin/html2pdf/strategy.width.max.php,0664,
pub/System/ToPDFPlugin/html2pdf/encoding.iso-8859-5.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.font-size.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/encoding.dingbats.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/encoding.windows-1251.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/encoding.entities.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/encoding.iso-8859-9.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.ruleset.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/xhtml.lists.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/output.pcl.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/inline.content.builder.nowrap.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.display.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.right.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/classes/org/active-link/xml/Tree.php,0664,
pub/System/ToPDFPlugin/html2pdf/classes/org/active-link/xml/Branch.php,0664,
pub/System/ToPDFPlugin/html2pdf/classes/org/active-link/xml/XMLRPCClient.php,0664,
pub/System/ToPDFPlugin/html2pdf/classes/org/active-link/xml/XMLBranch.php,0664,
pub/System/ToPDFPlugin/html2pdf/classes/org/active-link/xml/Leaf.php,0664,
pub/System/ToPDFPlugin/html2pdf/classes/org/active-link/xml/XPath.php,0664,
pub/System/ToPDFPlugin/html2pdf/classes/org/active-link/xml/XML.php,0664,
pub/System/ToPDFPlugin/html2pdf/classes/org/active-link/xml/XMLLeaf.php,0664,
pub/System/ToPDFPlugin/html2pdf/classes/org/active-link/xml/XMLDocument.php,0664,
pub/System/ToPDFPlugin/html2pdf/classes/org/active-link/xml/RSS.php,0664,
pub/System/ToPDFPlugin/html2pdf/classes/org/active-link/xml/Tag.php,0664,
pub/System/ToPDFPlugin/html2pdf/classes/org/active-link/sys/File.php,0664,
pub/System/ToPDFPlugin/html2pdf/classes/org/active-link/net/HTTPServer.php,0664,
pub/System/ToPDFPlugin/html2pdf/classes/org/active-link/net/Socket.php,0664,
pub/System/ToPDFPlugin/html2pdf/classes/org/active-link/net/HTTPClient.php,0664,
pub/System/ToPDFPlugin/html2pdf/classes/org/active-link/doc/DocHTML.php,0664,
pub/System/ToPDFPlugin/html2pdf/classes/org/active-link/doc/PHPClass.php,0664,
pub/System/ToPDFPlugin/html2pdf/classes/org/active-link/doc/Method.php,0664,
pub/System/ToPDFPlugin/html2pdf/classes/include.php,0664,
pub/System/ToPDFPlugin/html2pdf/value.border.edge.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.vertical-align.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/path.point.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.font-style.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/value.margin.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.cache.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.property.declaration.php,0664,
pub/System/ToPDFPlugin/html2pdf/box.frame.php,0664,
pub/System/ToPDFPlugin/html2pdf/output._interface.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.border.left.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/css/interface.parser.php,0664,
pub/System/ToPDFPlugin/html2pdf/css/interface.lexer.php,0664,
pub/System/ToPDFPlugin/html2pdf/css/stream.string.php,0664,
pub/System/ToPDFPlugin/html2pdf/css/class.stylesheet.property.php,0664,
pub/System/ToPDFPlugin/html2pdf/css/class.stylesheet.unary.operator.php,0664,
pub/System/ToPDFPlugin/html2pdf/css/class.stylesheet.ruleset.collection.php,0664,
pub/System/ToPDFPlugin/html2pdf/css/class.stylesheet.media.php,0664,
pub/System/ToPDFPlugin/html2pdf/css/class.stylesheet.operator.php,0664,
pub/System/ToPDFPlugin/html2pdf/css/class.stylesheet.selector.php,0664,
pub/System/ToPDFPlugin/html2pdf/css/state.stylesheet.php,0664,
pub/System/ToPDFPlugin/html2pdf/css/class.stylesheet.selector.collection.php,0664,
pub/System/ToPDFPlugin/html2pdf/css/lexer.php,0664,
pub/System/ToPDFPlugin/html2pdf/css/processor.php,0664,
pub/System/ToPDFPlugin/html2pdf/css/parser.php,0664,
pub/System/ToPDFPlugin/html2pdf/css/class.stylesheet.page.php,0664,
pub/System/ToPDFPlugin/html2pdf/css/class.stylesheet.php,0664,
pub/System/ToPDFPlugin/html2pdf/css/class.stylesheet.attrib.php,0664,
pub/System/ToPDFPlugin/html2pdf/css/interface.processor.php,0664,
pub/System/ToPDFPlugin/html2pdf/css/class.stylesheet.combinator.php,0664,
pub/System/ToPDFPlugin/html2pdf/css/class.stylesheet.declaration.php,0664,
pub/System/ToPDFPlugin/html2pdf/css/class.stylesheet.term.php,0664,
pub/System/ToPDFPlugin/html2pdf/css/class.stylesheet.declaration.collection.php,0664,
pub/System/ToPDFPlugin/html2pdf/css/class.stylesheet.ruleset.php,0664,
pub/System/ToPDFPlugin/html2pdf/css/class.stylesheet.expr.php,0664,
pub/System/ToPDFPlugin/html2pdf/css/class.stylesheet.simple.selector.php,0664,
pub/System/ToPDFPlugin/html2pdf/css/parser.error.php,0664,
pub/System/ToPDFPlugin/html2pdf/css/tokens.php,0664,
pub/System/ToPDFPlugin/html2pdf/css/legacy/css.parse.atpage.php,0664,
pub/System/ToPDFPlugin/html2pdf/css/legacy/css.parse.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/css/legacy/css.parse.properties.php,0664,
pub/System/ToPDFPlugin/html2pdf/css/legacy/css.parse.ruleset.php,0664,
pub/System/ToPDFPlugin/html2pdf/css/class.stylesheet.pseudo.php,0664,
pub/System/ToPDFPlugin/html2pdf/css/interface.stream.php,0664,
pub/System/ToPDFPlugin/html2pdf/css/class.stylesheet.import.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.pseudo.align.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/filter.data.utf8.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/fetched_data.url.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.page-break.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.list-style.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.height.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/path.rectangle.php,0664,
pub/System/ToPDFPlugin/html2pdf/inline.content.builder.normal.php,0664,
pub/System/ToPDFPlugin/html2pdf/box.list-item.php,0664,
pub/System/ToPDFPlugin/html2pdf/value.color.php,0664,
pub/System/ToPDFPlugin/html2pdf/ps.image.encoder.stream.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/config.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/media.layout.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/fonts/couri.afm,0664,
pub/System/ToPDFPlugin/html2pdf/fonts/cour.afm,0664,
pub/System/ToPDFPlugin/html2pdf/fonts/ariali.afm,0664,
pub/System/ToPDFPlugin/html2pdf/fonts/symbol.afm,0664,
pub/System/ToPDFPlugin/html2pdf/fonts/timesi.afm,0664,
pub/System/ToPDFPlugin/html2pdf/fonts/arialbd.afm,0664,
pub/System/ToPDFPlugin/html2pdf/fonts/times.afm,0664,
pub/System/ToPDFPlugin/html2pdf/fonts/print_glyphs.ps,0664,
pub/System/ToPDFPlugin/html2pdf/fonts/arialbi.afm,0664,
pub/System/ToPDFPlugin/html2pdf/fonts/courbi.afm,0664,
pub/System/ToPDFPlugin/html2pdf/fonts/courbd.afm,0664,
pub/System/ToPDFPlugin/html2pdf/fonts/timesbi.afm,0664,
pub/System/ToPDFPlugin/html2pdf/fonts/timesbd.afm,0664,
pub/System/ToPDFPlugin/html2pdf/globals.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.list-style-type.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.pseudo.link.target.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/favicon.ico,0664,
pub/System/ToPDFPlugin/html2pdf/css.pseudo.localalign.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.pseudo.form.action.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/tag.select.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/filter.pre.fields.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.max-height.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/value.right.php,0664,
pub/System/ToPDFPlugin/html2pdf/temp/.ignore,0664,
pub/System/ToPDFPlugin/html2pdf/css.counter.collection.php,0664,
pub/System/ToPDFPlugin/html2pdf/strategy.width.max.natural.php,0664,
pub/System/ToPDFPlugin/html2pdf/box.generic.php,0664,
pub/System/ToPDFPlugin/html2pdf/strategy.position.absolute.php,0664,
pub/System/ToPDFPlugin/html2pdf/width.constraint.php,0664,
pub/System/ToPDFPlugin/html2pdf/ps.utils.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.border.top.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/destinations/null.php,0664,
pub/System/ToPDFPlugin/html2pdf/encoding.iso-8859-3.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.html2ps.html.content.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.list-style-position.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.left.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.property.sub.field.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.state.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.border.width.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/box.field.pages.php,0664,
pub/System/ToPDFPlugin/html2pdf/output.fastps.l2.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/stubs.is_executable.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/ps.l2.image.encoder.stream.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/pipeline.factory.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.parse.media.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/value.text-indent.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/height.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.list-style-image.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/inline.content.builder.php,0664,
pub/System/ToPDFPlugin/html2pdf/utils_graphic.php,0664,
pub/System/ToPDFPlugin/html2pdf/pdf.fpdf.php,0664,
pub/System/ToPDFPlugin/html2pdf/error.php,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/box.block.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/border.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/box.generic.inline.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/encoding.iso-8859-10.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/box.table.cell.fake.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/encoding.windows-1250.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/box.text.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/background.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/box.container.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/encoding.iso-8859-15.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/height.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/init.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/flow.inline.block.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/cellspan.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/fastps.footer.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/box.input.check.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/box.frame.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/image.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/box.table.row.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/flow.block.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/box.image.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/box.block.inline.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/text-align.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/position.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/context.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/box.inline.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/table.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/encoding.dingbats.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/box.radiobutton.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/encoding.iso-8859-7.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/fastps.header.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/flow_viewport.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/array.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/box.generic.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/encoding.iso-8859-2.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/viewport.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/box.input.text.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/encoding.windows-1251.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/predicates.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/box.iframe.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/box.span.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/table.row.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/flow.table.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/box.list-item.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/encoding.symbol.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/box.table.cell.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/encoding.iso-8859-4.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/footer.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/box.table.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/font.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/width.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/containing_block.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/encoding.windows-1252.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/encoding.iso-8859-3.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/encoding.iso-8859-13.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/header.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/encoding.koi8-r.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/flow.legend.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/box.button.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/box.input.radio.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/flow.float.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/box.inline.whitespace.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/color.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/class.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/encoding.iso-8859-11.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/encoding.iso-8859-14.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/box.checkbutton.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/geometry.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/background.image.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/vertical-align.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/encoding.iso-8859-9.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/box.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/encoding.iso-8859-5.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/flow.box.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/flow.inline.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/box.break.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/box.select.ps,0664,
pub/System/ToPDFPlugin/html2pdf/postscript/box.whitespace.ps,0664,
pub/System/ToPDFPlugin/html2pdf/css.font-family.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/tag.utils.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/layout._interface.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.border.style.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/filter.output.gzip.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/TODO,0664,
pub/System/ToPDFPlugin/html2pdf/layout.default.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/encoding.glyphs.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/filter.data.xhtml2xhtml.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/doc.anchor.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/box.checkbutton.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.letter-spacing.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/help/internals_reserved.html,0664,
pub/System/ToPDFPlugin/html2pdf/help/forms.html,0664,
pub/System/ToPDFPlugin/html2pdf/help/api_samples.html,0664,
pub/System/ToPDFPlugin/html2pdf/help/generated_toc.html,0664,
pub/System/ToPDFPlugin/html2pdf/help/api_dom.html,0664,
pub/System/ToPDFPlugin/html2pdf/help/compatibility.css.3.html,0664,
pub/System/ToPDFPlugin/html2pdf/help/api_events.html,0664,
pub/System/ToPDFPlugin/html2pdf/help/misc.html,0664,
pub/System/ToPDFPlugin/html2pdf/help/howto_fonts.html,0664,
pub/System/ToPDFPlugin/html2pdf/help/compatibility.css.2.1.html,0664,
pub/System/ToPDFPlugin/html2pdf/help/calling.html,0664,
pub/System/ToPDFPlugin/html2pdf/help/UML/Simple_custom_fetcher_session.png,0664,
pub/System/ToPDFPlugin/html2pdf/help/UML/Custom_fetcher_session.png,0664,
pub/System/ToPDFPlugin/html2pdf/help/UML/Post_filters.PNG,0664,
pub/System/ToPDFPlugin/html2pdf/help/UML/Output_drivers.PNG,0664,
pub/System/ToPDFPlugin/html2pdf/help/UML/Pre_filters.PNG,0664,
pub/System/ToPDFPlugin/html2pdf/help/UML/Data_filters.PNG,0664,
pub/System/ToPDFPlugin/html2pdf/help/UML/Output_filters.PNG,0664,
pub/System/ToPDFPlugin/html2pdf/help/UML/Multiple_fetcher_session.PNG,0664,
pub/System/ToPDFPlugin/html2pdf/help/UML/Destinations.PNG,0664,
pub/System/ToPDFPlugin/html2pdf/help/UML/Simple_fetcher_session.PNG,0664,
pub/System/ToPDFPlugin/html2pdf/help/UML/Fetchers.PNG,0664,
pub/System/ToPDFPlugin/html2pdf/help/UML/Layout_engines.PNG,0664,
pub/System/ToPDFPlugin/html2pdf/help/UML/Parsers.PNG,0664,
pub/System/ToPDFPlugin/html2pdf/help/directives.html,0664,
pub/System/ToPDFPlugin/html2pdf/help/api.html,0664,
pub/System/ToPDFPlugin/html2pdf/help/faq.html,0664,
pub/System/ToPDFPlugin/html2pdf/help/samples/headfoot.html,0664,
pub/System/ToPDFPlugin/html2pdf/help/howto_afm.html,0664,
pub/System/ToPDFPlugin/html2pdf/help/internals_pagebreak.html,0664,
pub/System/ToPDFPlugin/html2pdf/help/css/help.css,0664,
pub/System/ToPDFPlugin/html2pdf/help/configuration.html,0664,
pub/System/ToPDFPlugin/html2pdf/help/index.html,0664,
pub/System/ToPDFPlugin/html2pdf/help/requirements.html,0664,
pub/System/ToPDFPlugin/html2pdf/help/api_fetchers.html,0664,
pub/System/ToPDFPlugin/html2pdf/help/install.html,0664,
pub/System/ToPDFPlugin/html2pdf/filter.pre.height-constraint.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/filter.output._interface.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.float.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/strategy.page.break.smart.php,0664,
pub/System/ToPDFPlugin/html2pdf/css.z-index.inc.php,0664,
pub/System/ToPDFPlugin/html2pdf/destination._interface.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/destination.download.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/filter.pre._interface.class.php,0664,
pub/System/ToPDFPlugin/html2pdf/value.generic.percentage.php,0664,
pub/System/ToPDFPlugin/html2pdf/dom.php4.inc.php,0664,
pub/System/ToPDFPlugin/topdf.php,0664,

<<<< DEPENDENCIES >>>>
HTTP::Cookies::Find,>0,1,cpan,Required
Encode,>0,1,cpan,Required
Encode::Encoding,>0,1,cpan,Required
File::Basename,>0,1,cpan,Required
URI::Escape,>0,1,cpan,Required
HTML::TreeBuilder,>0,1,cpan,Required

